springdoc:
  swagger-ui:
    path: "/"
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: "jdbc:h2:file:~/framework-db"
    driver-class-name: org.h2.Driver
    username: "oopframework"
    password: ""
  h2:
    console:
      enabled: true
      path: "/h2"
