server:
  port: 8080

springdoc:
  swagger-ui:
    path: "/"
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.temp.usi_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
  datasource:
    url: url
    username: secret
    password: secret

rsa:
  private-key: "classpath:certs/private.pem"
  public-key: "classpath:certs/public.pem"
