server:
  port: 8080

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.temp.usi_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://postgres-service:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

rsa:
  private-key: "classpath:certs/private.pem"
  public-key: "classpath:certs/public.pem"
